#!/usr/bin/env bash
# check_phase_1.sh — Gate check for Phase 1 — Scanner Engine
# AUTO-GENERATED by gen_phase_gates.py from project.yaml
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "=== Phase 1 — Scanner Engine ==="
echo ''

PASSED=0
FAILED=0
ERRORS=()

echo -n "  [1/1] Model scanner dry-run passes... "
if python scripts/run_model_scan.py --dry-run > /dev/null 2>&1; then
    echo "PASS"
    PASSED=$((PASSED + 1))
else
    echo "FAIL"
    FAILED=$((FAILED + 1))
    ERRORS+=("  FAIL: Model scanner dry-run passes")
    ERRORS+=("        Command: python scripts/run_model_scan.py --dry-run")
fi

echo ''
echo "=== Results: $PASSED passed, $FAILED failed ==="

if [ $FAILED -gt 0 ]; then
    echo ""
    echo "Failures:"
    for err in "${ERRORS[@]}"; do
        echo "$err"
    done
    echo ""
    echo "Phase gate FAILED. Fix the above issues before proceeding."
    exit 1
fi

echo "Phase 1 — Scanner Engine — ALL CHECKS PASSED"
